codecov:
  token: 7fe199ac-ee2b-4a80-b21f-17a9c37af37d
ignore:
  - "Pyrado/doc"
  - "Pyrado/pyrado/environments/barrett_wam"
  - "Pyrado/pyrado/environments/mujoco"
  - "Pyrado/scripts"
  - "Pyrado/tests"
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false # if true: only post the comment if coverage changes
  require_base: no # [yes :: must have a base report to post]
  require_head: yes # [yes :: must have a head report to post]
  branches: # branch names that can post comment
    - "master"
github_checks:
  annotations: false
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
