codecov:
  token: 7fe199ac-ee2b-4a80-b21f-17a9c37af37d
ignore:
  - "Pyrado/data"
  - "Pyrado/doc"
  - "Pyrado/pyrado/environments/barrett_wam"
  - "Pyrado/pyrado/environments/mujoco"
  - "Pyrado/pyrado/environments/quanser"
  - "Pyrado/pyrado/environments/gym_wrapper"
  - "Pyrado/scripts"
  - "Pyrado/setup.py"
  - "RcsPySim/doc"
  - "RcsPySim/config"
  - "thirdParty"
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false # if true: only post the comment if coverage changes
  require_base: no # [yes :: must have a base report to post]
  require_head: yes # [yes :: must have a head report to post]
  branches: # branch names that can post comment
    - "master"
github_checks:
  annotations: false
coverage:
  status:
    project:
      default:
        target: auto # minimum coverage ratio that the commit must meet to be considered a success
        threshold: 5% # allow the coverage to drop by X%, and posting a success status
        if_ci_failed: error # success, failure, error, or ignore
    patch: # about the individual commit
      default:
        target: 30% # minimum coverage ratio that the commit must meet to be considered a success
        threshold: 0% # allow the coverage to drop by X%, and posting a success status
        if_ci_failed: error # success, failure, error, or ignore
