name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Checking for code conformity with Black
    runs-on: ubuntu-latest
    env:
      working-directory: ./Pyrado
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
