name: Docker Workflow

on:
  push:
    branches: [ master, cicd ]
  pull_request:
    branches: [ master, cicd ]

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [sacher, blackforest, malakoff, redvelvet]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: famura/simurlacra:${{matrix.flavor}}
          file: docker/Dockerfile.${{matrix.flavor}}
