name: Deploy Documentation

on:
  workflow_run:
    workflows: ["Publish Docker Images"]
    branches: [cicd, master]
    types: [completed]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Build Docs
        continue-on-error: true
        run: |
          mkdir public
          export PUBLIC=$(realpath ./public)
          docker run --rm -u 1000:1000 -v $PUBLIC:/var/www ghcr.io/famura/simurlacra:sacher conda run -n pyrado bash -c "./build_docs.sh;sudo mkdir /var/www/pyrado; sudo cp -r Pyrado/doc/build/* /var/www/pyrado;mv RcsPySim/build/doc/html RcsPySim/build/doc/rcspysim; sudo cp -r RcsPySim/build/doc/rcspysim /var/www"
          echo $PUBLIC
      - name: Deploy
        continue-on-error: true
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
