name: Publish Docker Images On Release

on:
  release:

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [sacher, blackforest, malakoff, redvelvet]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            simurlacra/simurlacra:${{ matrix.flavor }}-${{GITHUB_REF#refs/*/}}
            ghcr.io/${{ github.repository_owner }}/simurlacra:${{ matrix.flavor }}-${{GITHUB_REF#refs/*/}}
          build-args: |
            OPTION=${{ matrix.flavor }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/simurlacra:${{ matrix.flavor }}
          cache-to: type=inline
