name: PyLint

on: [push, pull_request]

jobs:
  lint:
    name: Checking for code conformity with PyBlack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: python -m pip install --upgrade pylint
      - name: PyLint
        run: pylint Pyrado
